using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SynlessKeyboardMapper
{
    public static class KeyToString
    {
        public static Dictionary<string, string> forward = new Dictionary<string, string>()
        {
            {"A","L_A"},
            {"B","L_B"},
            {"C","L_C"},
            {"D","L_D"},
            {"E","L_E"},
            {"F","L_F"},
            {"G","L_G"},
            {"H","L_H"},
            {"I","L_I"},
            {"J","L_J"},
            {"K","L_K"},
            {"L","L_L"},
            {"M","L_M"},
            {"N","L_N"},
            {"O","L_O"},
            {"P","L_P"},
            {"Q","L_Q"},
            {"R","L_R"},
            {"S","L_S"},
            {"T","L_T"},
            {"U","L_U"},
            {"V","L_V"},
            {"W","L_W"},
            {"X","L_X"},
            {"Y","L_Y"},
            {"Z","L_Z"},

            {"F1","F_1"},
            {"F2","F_2"},
            {"F3","F_3"},
            {"F4","F_4"},
            {"F5","F_5"},
            {"F6","F_6"},
            {"F7","F_7"},
            {"F8","F_8"},
            {"F9","F_9"},
            {"F10","F_10"},
            {"F11","F_11"},
            {"F12","F_12"},

            {"D0","D_0"},
            {"D1","D_1"},
            {"D2","D_2"},
            {"D3","D_3"},
            {"D4","D_4"},
            {"D5","D_5"},
            {"D6","D_6"},
            {"D7","D_7"},
            {"D8","D_8"},
            {"D9","D_9"},

            {"NumPad0","N_0"},
            {"NumPad1","N_1"},
            {"NumPad2","N_2"},
            {"NumPad3","N_3"},
            {"NumPad4","N_4"},
            {"NumPad5","N_5"},
            {"NumPad6","N_6"},
            {"NumPad7","N_7"},
            {"NumPad8","N_8"},
            {"NumPad9","N_9"},
            {"Divide","N_D"},
            {"Add","N_A"},
            {"Subtract","N_S"},
            {"Multiply","N_M"},
            {"Decimal","N_P"},
            {"NumLock","N_L"},


            {"Up","A_U"},
            {"Right","A_R"},
            {"Down","A_D"},
            {"Left","A_L"},

            {"Escape","S_ESC"},
            {"Tab","S_TAB"},
            {"LeftShift","S_LSHIFT"},
            {"RightShift","S_RSHIFT"},
            {"LeftCtrl","S_LCTRL"},
            {"RightCtrl","S_RCTRL"},
            {"Capital","S_CAPS"},
            {"LWin","S_LWIN"},
            {"RWin","S_RWIN"},
            {"System","S_ALT"},
            {"Apps","S_APPS"},
            {"Insert","S_INSERT"},
            {"Back","S_BACK"},
            {"Home","S_HOME"},
            {"PageUp","S_UP"},
            {"End","S_END"},
            {"Scroll","S_SCROLL" },
            {"Pause","S_PAUSE" },
            {"Space","S_SPACE" },
            {"Return","S_ENTER" },

            {"OemQuotes","OEM_Q"},
            {"Oem1","OEM_1"},
            {"Oem2","OEM_2"},
            {"Oem3","OEM_3"},
            {"Oem4","OEM_4"},
            {"Oem5","OEM_5"},
            {"Oem6","OEM_6"},
            {"Oem7","OEM_7"},
            {"Oem8","OEM_8"},
            {"OemBackslash","OEM_B"},
            {"OemPlus","OEM_PLUS"},
            {"OemComma","OEM_C"},
            {"OemQuestion","OME_Q" },
            {"OemPeriod","OME_P" },
        };
        public static Dictionary<string, string> backward = new Dictionary<string, string>()
        {
            {"A","L_A"},
            {"B","L_B"},
            {"C","L_C"},
            {"D","L_D"},
            {"E","L_E"},
            {"F","L_F"},
            {"G","L_G"},
            {"H","L_H"},
            {"I","L_I"},
            {"J","L_J"},
            {"K","L_K"},
            {"L","L_L"},
            {"M","L_M"},
            {"N","L_N"},
            {"O","L_O"},
            {"P","L_P"},
            {"Q","L_Q"},
            {"R","L_R"},
            {"S","L_S"},
            {"T","L_T"},
            {"U","L_U"},
            {"V","L_V"},
            {"W","L_W"},
            {"X","L_X"},
            {"Y","L_Y"},
            {"Z","L_Z"},

            {"F1","F_1"},
            {"F2","F_2"},
            {"F3","F_3"},
            {"F4","F_4"},
            {"F5","F_5"},
            {"F6","F_6"},
            {"F7","F_7"},
            {"F8","F_8"},
            {"F9","F_9"},
            {"F10","F_10"},
            {"F11","F_11"},
            {"F12","F_12"},

            {"D0","D_0"},
            {"D1","D_1"},
            {"D2","D_2"},
            {"D3","D_3"},
            {"D4","D_4"},
            {"D5","D_5"},
            {"D6","D_6"},
            {"D7","D_7"},
            {"D8","D_8"},
            {"D9","D_9"},

            {"NumPad0","N_0"},
            {"NumPad1","N_1"},
            {"NumPad2","N_2"},
            {"NumPad3","N_3"},
            {"NumPad4","N_4"},
            {"NumPad5","N_5"},
            {"NumPad6","N_6"},
            {"NumPad7","N_7"},
            {"NumPad8","N_8"},
            {"NumPad9","N_9"},
            {"Divide","N_D"},
            {"Add","N_A"},
            {"Subtract","N_S"},
            {"Multiply","N_M"},
            {"Decimal","N_P"},
            {"NumLock","N_L"},


            {"Up","A_U"},
            {"Right","A_R"},
            {"Down","A_D"},
            {"Left","A_L"},

            {"Escape","S_ESC"},
            {"Tab","S_TAB"},
            {"LeftShift","S_LSHIFT"},
            {"RightShift","S_RSHIFT"},
            {"LeftCtrl","S_LCTRL"},
            {"RightCtrl","S_RCTRL"},
            {"Capital","S_CAPS"},
            {"LWin","S_LWIN"},
            {"RWin","S_RWIN"},
            {"System","S_ALT"},
            {"Apps","S_APPS"},
            {"Insert","S_INSERT"},
            {"Back","S_BACK"},
            {"Home","S_HOME"},
            {"PageUp","S_UP"},
            {"End","S_END"},
            {"Scroll","S_SCROLL" },
            {"Pause","S_PAUSE" },
            {"Space","S_SPACE" },
            {"Return","S_ENTER" },

            {"OemQuotes","OEM_Q"},
            {"Oem1","OEM_1"},
            {"Oem2","OEM_2"},
            {"Oem3","OEM_3"},
            {"Oem5","OEM_5"},
            {"Oem6","OEM_6"},
            {"Oem8","OEM_8"},
            {"OemBackslash","OEM_B"},
            {"OemPlus","OEM_PLUS"},
            {"OemComma","OEM_C"},
            {"OemQuestion","OME_Q" },
            {"OemPeriod","OME_P" },
        };
    }
}
